### ISSUE TITLE
crémaillère

### ISSUE THREAD

**Issue by vincenthirtz** [romainrhd/v2#1]
Est-ce que la v2 a pensé à inviter bibi ?

**Comment by vincenthirtz** [comment]
On peut s'organiser pour un airbnb

**Comment by romainrhd** [comment]
C'est compliqué surtout que en juin, je vais certainement déménager de nouveau. Autant faire dans le projet qui sera l'endroit où je m'installe pour quelques années

**Comment by vincenthirtz** [comment]
pd

**Comment by romainrhd** [comment]
¯\_(ツ)_/¯
